### ISSUE TITLE
Make empty key give the same result as no key

### ISSUE THREAD

**Issue by bwesterb** [dchest/pyblake2#5]
`pyblake.blake2b('', '')` does not equal `pyblake.blake2b('')`.

**Comment by dchest** [comment]
Yes, empty key is handled as a keyed hash function with zero-length key, which is different from not having a key, because in this case the first data block is set to the "key" padded with zeros (i.e all zeros). The BLAKE2 spec says that key length in the parameter block should be set to 0 if there's no key, but doesn't say what to do if the key present but is zero-length. In both pyblake2 and blake2 Go packages I interpreted the latter case to still set key length 0 zero and continue processing as if we have a key, which I think is a correct choice.

So, it's up to the package users to select the proper hash function they need: a keyed or unkeyed one. I should also note that your examples should read:

> `pyblake2.blake2b('')` does not equal `pyblake2.blake2b('', key='')` 
> (or `b''` if using Python 3)

Thus, there should be no confusion for programmers on which function is used.

**Comment by dchest** [comment]
Reopening to remember to document this behaviour. (For reference: BLAKE2 designers consider zero-key == no key).

**Comment by dchest** [comment]
Fixed in 1.0.0
