### ISSUE TITLE
Provide Windows packaged version

### ISSUE THREAD

**Issue by Alex131089** [dchest/pyblake2#9]
Is it possible to provide prepackaged (wheel) version for windows ?

**Comment by dchest** [comment]
I know nothing about Python on Windows, so any contributions are welcome.

**Comment by dchest** [comment]
I know nothing about Python on Windows, so any contributions are welcome.

**Comment by dchest** [comment]
(Oops, closed accidentally; reopened)

**Comment by matejcik** [comment]
could you please trigger the build to generate wheels for python 3.7 ?

**Comment by dchest** [comment]
@matejcik I tried, but AppVeyor prints this when building:

```
Build started
git clone -q --branch=master https://github.com/dchest/pyblake2.git C:\projects\pyblake2
git checkout -qf f46997b9aa4a11026b8b1aca2dbbef08904f2e78
The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command.
```

Tried a few things, but it didn't work... maybe they changed config format. It won't even build the previous version. I don't know how to solve this.

BTW, if you're writing something for Py>3.6, please use build-in `hashlib.blake2b`/`hashlib.blake2s`: in fact, since they are compatible (hashlib implementation is based on this module), you can even conditionally import them instead of `pyblake2` for Py3.6 and later versions. I understand that this is not an option for users of third-party software though.

**Comment by matejcik** [comment]
Ha, I didn't know about blake2 being in stdlib. That solves my problem nicely at least.
It would be good to have this information on the pypi page directly. But I presume that you'd have to do a new release to edit that.
